<?php

/**
 * AirCompanyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AirCompanyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AirCompanyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AirCompany');
    }
}