<?php

/**
 * FoodReorderedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FoodReorderedTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FoodReorderedTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FoodReordered');
    }
}