<?php

/**
 * RelCultureTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RelCultureTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RelCultureTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RelCulture');
    }
}