<?php

/**
 * RelCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RelCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RelCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RelCategory');
    }
}