<?php

/**
 * RelSiteCultureTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RelSiteCultureTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RelSiteCultureTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RelSiteCulture');
    }
}