<?php

/**
 * RelSiteSettingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RelSiteSettingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return RelSiteSettingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RelSiteSetting');
    }
}