<?php

/**
 * SkipOnColumnUpdateTestTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SkipOnColumnUpdateTestTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SkipOnColumnUpdateTestTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SkipOnColumnUpdateTest');
    }
}