<?php

/**
 * TreeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TreeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TreeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tree');
    }
}